all:
  children:
    superset_servers:
      hosts:
        superset-server:
          ansible_host: 34.151.111.45
          ansible_user: mac
          ansible_ssh_private_key_file: ~/.ssh/at-bus-superset-key