all:
  children:
    superset_servers:
      hosts:
        superset-server:
          ansible_host: 35.197.173.72
          ansible_user: mac
          ansible_ssh_private_key_file: ~/.ssh/at-bus-superset-key