---
- name: Update Superset to New Version
  hosts: superset_servers
  become: yes
  gather_facts: yes
  
  vars_files:
    - group_vars/all.yml

  vars:
    # Set this to the new version you want to upgrade to
    new_superset_version: "5.0.0"

  tasks:
    - name: Validate new version parameter
      fail:
        msg: "Please set the 'new_superset_version' variable to specify the version to upgrade to"
      when: new_superset_version == ""

    - name: Display current and new version
      debug:
        msg: |
          Current Superset Version: {{ superset_version }}
          New Superset Version: {{ new_superset_version }}

    - name: Create backup before update
      include_tasks: backup.yml

    - name: Update Superset version in variables
      set_fact:
        superset_version: "{{ new_superset_version }}"
        superset_image: "apache/superset:{{ new_superset_version }}-dev"
        superset_init_image: "apache/superset:{{ new_superset_version }}-dev"

    - name: Update Superset configuration
      template:
        src: templates/superset_config.py.j2
        dest: "{{ superset_install_dir }}/superset_config.py"
        mode: '0644'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        backup: yes

    - name: Update Docker Compose file
      template:
        src: docker-compose.yml.j2
        dest: "{{ superset_install_dir }}/docker-compose.yml"
        mode: '0644'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        backup: yes

    - name: Update environment file
      template:
        src: templates/env.j2
        dest: "{{ superset_install_dir }}/.env"
        mode: '0644'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        backup: yes

    - name: Pull new Docker images
      community.docker.docker_compose_v2:
        project_src: "{{ superset_install_dir }}"
        pull: always
        build: never

    - name: Stop current Superset services
      community.docker.docker_compose_v2:
        project_src: "{{ superset_install_dir }}"
        state: absent
      ignore_errors: yes

    - name: Start updated Superset services
      community.docker.docker_compose_v2:
        project_src: "{{ superset_install_dir }}"
        state: present
        build: never

    - name: Wait for services to be ready
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ superset_port }}"
        delay: 10
        timeout: 300

    - name: Run database migrations
      community.docker.docker_compose_v2:
        project_src: "{{ superset_install_dir }}"
        profiles: ["init"]
        state: present
        build: never

    - name: Verify Superset is running
      uri:
        url: "http://{{ ansible_host }}:{{ superset_port }}/health"
        method: GET
        status_code: 200
      register: health_check
      retries: 5
      delay: 10
      until: health_check.status == 200

    - name: Display update information
      debug:
        msg: |
          ========================================
          Superset Update Completed Successfully!
          ========================================
          
          Previous Version: {{ superset_version }}
          New Version: {{ new_superset_version }}
          
          Access URL: http://{{ ansible_host }}:{{ superset_port }}
          Installation Directory: {{ superset_install_dir }}
          
          ========================================
          IMPORTANT: Test your dashboards and data!
          ======================================== 